websitesDictWithChancelleryName={
"gansel" : "https://www.gansel-rechtsanwaelte.de/",
"illner" : "http://www.kanzlei-illner.de/",
"heinz" : "http://www.hpk-recht.de/",
"himmelmann" : "https://www.himmelmann-pohlmann.de/",
"dressler" : "http://www.anwaltskanzlei-dressler.de/",
"wolff" : "http://www.anwalt.de/wolff-partner",
"advopartner" : "http://www.advopartner.de/",
"mayer" : "http://www.anwaelte-mayer.com/",
"platanenhof" : "http://www.kanzlei-platanenhof.de/",
"teigelack" : "http://www.rae-teigelack.de/",
"matyssek" : "http://www.matyssek-kirchmann.de/",
"keller" : "http://www.rae-drkeller.de/",
"heimbürger" : "http://www.hp-verteidigung.de/",
"steinhauer" : "http://www.sws-rechtsanwaelte.de/",
"nerger" : "http://www.anb-anwaelte.de/",
"wittenberg" : "http://www.wittenberg-kollegen.de/",
"hering" : "http://www.kanzlei-hzk.de/",
"puhr" : "http://www.ra-npp.de/",
"gärtner" : "http://www.kanzlei-duisburg.de/",
"keller" : "http://www.rae-drkeller.de/",
"hauser" : "http://www.zum-recht.de/",
"andries" : "http://www.andries-collegen.de/",
"kemper" : "http://www.kemper-hein.de/",
"döttelbeck" : "http://www.doettelbeck.de/",
"ohliger" : "http://www.ol-sg.de/",
"rellecke" : "http://www.anwaelte-solingen.de/",
"linten" : "http://www.linten.de/",
"wupperAdvokaten" : "http://www.wupperadvokaten.de/",
"Daams, Singer, Jonas-loga" : "http://www.kanzlei-daams.de/",
"Velder Cremer Weiler Alms" : "http://www.ra.kanzlei-vcw.de/",
"Altemann, Niemeyer, Schmidt & Partner" : "http://www.altemann.de/",
"Badde Lackner Kerkhoff" : "http://www.kanzlei-bottrop.de/",
"Heimbürger & Partner" : "http://www.hp-verteidigung.de/",
"Steinhauer, Wilden, Simon" : "http://www.sws-rechtsanwaelte.de/"
}